server:
  port: 8090

spring:
  config:
    activate:
      on-profile: dev1
---

server:
  port: 8091

spring:
  config:
    activate:
      on-profile: test1

---

server:
  port: 8092

spring:
  config:
    activate:
      on-profile: pro1
---

spring:
  profiles:
    active: dev1